[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.black]
include ='\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | build
  | dist
  | __pycache__
  | .eggs
)/
'''
target-version = ['py38']
line-length = 90
