global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'mite'
    static_configs:
      - targets: ['mite_prometheus_exporter_1:9301'] # this address must equal the mite prometheus_exporter --web-address arg